#pragma once
#include "object.h"

#define CUBE_VERTICES_CONST 1.0f
#define EDGE_VERTICES_OFFSET 0.05f
#define BLACK_FLOATS 0.0f, 0.0f, 0.0f
#define WHITE_FLOATS 1.f, 1.f, 1.f

class Cube : public MeshObject {
public:
    const Vertex cubeVertices[8] = {
        // Front face
        { -CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, WHITE_FLOATS },
        { CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, WHITE_FLOATS },
        { CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, WHITE_FLOATS },
        { -CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, WHITE_FLOATS },

        // Back face
        { -CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, WHITE_FLOATS },
        { CUBE_VERTICES_CONST, -CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, WHITE_FLOATS },
        { CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, WHITE_FLOATS },
        { -CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, CUBE_VERTICES_CONST, WHITE_FLOATS }
    };
    const Vertex edgeVertices[24] = {
        // front face
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },

        // back face
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), BLACK_FLOATS },

        // left face
        { -(CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },

        // right face
        { (CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },

        // bottom face
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), -(CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },

        // top face
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS },
        { -(CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), (CUBE_VERTICES_CONST + 0.01f), (CUBE_VERTICES_CONST - EDGE_VERTICES_OFFSET), BLACK_FLOATS }
    };
    const unsigned int indices[36] = {
        0, 1, 2, 2, 3, 0, // Front face
        7, 6, 5, 5, 4, 7, // Back face
        4, 0, 3, 3, 7, 4, // bottom face
        5, 6, 2, 2, 1, 5, // top face
        1, 0, 4, 4, 5, 1, // left face
        3, 2, 6, 6, 7, 3 // right face
    };
    GLuint VAOs[7], VBOs[7], EBOs[7];
    const unsigned int faceIndices[6] = {0, 1, 2, 2, 3, 0};
    Cube(Shader* sh);
    ~Cube();
    Shader* shader;
    glm::mat4 projectionMatrix;
    glm::mat4 viewMatrix;
    glm::mat4 modelMatrix;
    
    void draw();
    void setProjectionMatrix(glm::mat4 projectionMatrix);
    void setViewMatrix(glm::vec3 viewMatrix);
    void setModelMatrix(glm::mat4 modelMatrix);
    void translate(glm::vec3 translation);
    void rotate(float angle, glm::vec3 axis);
    void scale(glm::vec3 scale);
    void uniformScale(float scale);
    void rotateAbout(float angle, glm::vec3 axis, glm::vec3 point);
};