// TODO: Go through this method by method and make sure everything makes sense. Most of this file
// was generated by copilot.

#include "dockerApi.h"

DockerAPI::DockerAPI(const std::string& base_url)
    : client(base_url)
    , base_url(base_url)
{

    std::string containers = this->getContainers_json();
    std::cout << "Containers: " << containers << std::endl;

    std::string images = this->getImages_json();
    std::cout << "Images: " << images << std::endl;
}

DockerAPI::DockerAPI()
    : client("http://127.0.0.1:2375")
    , base_url("http://127.0.0.1:2375")
{
    std::string containers = this->getContainers_json();
    std::cout << "Containers: " << containers << std::endl;

    std::string images = this->getImages_json();
    std::cout << "Images: " << images << std::endl;
}

std::string DockerAPI::getContainers_json()
{
    auto res = client.Get("/containers/json");
    if (res && res->status == 200) {
        return res->body;
    } else {
        return "Error: Unable to list containers";
    }
}

std::vector<std::string> DockerAPI::getContainers_vec()
{
    std::string containers = this->getContainers_json();
    nlohmann::json containers_json = nlohmann::json::parse(containers);
    std::vector<std::string> container_ids;
    for (auto container : containers_json) {
        container_ids.push_back(container["Id"]);
    }
    return container_ids;
}

std::string DockerAPI::getImages_json()
{
    auto res = client.Get("/images/json");
    if (res && res->status == 200) {
        return res->body;
    } else {
        return "Error: Unable to list images";
    }
}

std::expected<std::string, DockerError> DockerAPI::startContainer(const std::string& container_id)
{
    std::string endpoint = "/containers/" + container_id + "/start";
    auto res = client.Post(endpoint.c_str());
    if (res && res->status == 204) {
        return "Container started successfully";
    } else {
        return "Error: Unable to start container";
    }
}

std::expected<std::string, DockerError> DockerAPI::stopContainer(const std::string& container_id)
{
    std::string endpoint = "/containers/" + container_id + "/stop";
    auto res = client.Post(endpoint.c_str());
    if (res && res->status == 204) {
        return "Container stopped successfully";
    } else {
        return "Error: Unable to stop container";
    }
}

std::string DockerAPI::inspectContainer(const std::string& container_id)
{
    std::string endpoint = "/containers/" + container_id + "/json";
    auto res = client.Get(endpoint.c_str());
    if (res && res->status == 200) {
        return res->body;
    } else {
        return "Error: Unable to inspect container";
    }
}

bool DockerAPI::isContainerRunning(const std::string& container_id)
{
    std::string container = this->inspectContainer(container_id);
    nlohmann::json container_json = nlohmann::json::parse(container);
    return container_json["State"]["Running"];
}

std::expected<std::string, DockerError> DockerAPI::killContainer(const std::string& container_id)
{
    std::string endpoint = "/containers/" + container_id + "/kill";
    auto res = client.Post(endpoint.c_str());
    if (res && res->status == 204) {
        return "Container killed successfully";
    } else {
        return std::unexpected(DockerError("Error: Unable to kill container", DockerError::CONTAINER_KILL_ERROR));
    }
}