#include <globalSettings.h>

std::vector<std::pair<GlobalSettings::SettingType, std::function<void()>>> GlobalSettings::settingChangeCallbacks = {};
std::mutex GlobalSettings::settingChangeMutex;
nlohmann::json GlobalSettings::settings = nlohmann::json();
std::unordered_map <GlobalSettings::SettingType, std::string> GlobalSettings::settingTypeStringMap = {
        {LOG_VERBOSITY, "logVerbosity"},
        {SELECTED_FONT_PATH, "selectedFontPath"},
        {LOG_LEVEL_PRINT, "logLevelP"},
        {LOG_LEVEL_FILE, "logLevelF"},
        {DEVELOPER_MODE_ENABLED, "developerModeEnabled"},
        {CPU_AND_MEMORY_DISPLAY_ENABLED, "cpuAndMemoryDisplayEnabled"},
        {SSH_ENABLED, "sshEnabled"},
        {WIFI_ENABLED, "wifiEnabled"},
        {WIFI_SSID, "wifiSSID"},
        {WIFI_PASSWORD, "wifiPassword"},
        {BT_ENABLED, "btEnabled"},
        {STATUS_IP_ADDRESS, "statusIPAddress"},
        {STATUS_WIFI_MAC_ADDRESS, "statusWifiMACAddress"},
        {STATUS_BT_MAC_ADDRESS, "statusBTMACAddress"},
        {STATUS_FCC_ID, "statusFCCID"},
        {IDLE_ANIMATION_ENABLED, "idleAnimationEnabled"},
        {IDLE_ANIMATION, "idleAnimation"},
        {SCREEN_BRIGHTNESS, "screenBrightness"},
        {SCREEN_AUTO_OFF, "screenAutoOff"},
        {SCREEN_AUTO_OFF_TIME, "screenAutoOffTime"},
        {NOTIFICATIONS_FROM_NETWORK_ENABLED, "notificationsFromNetworkEnabled"},
        {SYSTEM_VOLUME, "systemVolume"},
        {NOTIFICATION_SOUND, "notificationSound"},
        {ALARM_SOUND, "alarmSound"},
        {VOICE_COMMAND_SOUND, "voiceCommandSound"},
        {NFC_ENABLED, "nfcEnabled"},
        {MICROPHONE_ENABLED, "microphoneEnabled"},
        {PRESENCE_DETECTION_ENABLED, "presenceDetectionEnabled"}
    };
std::unordered_map <std::string, GlobalSettings::SettingType> GlobalSettings::stringSettingTypeMap = {
        {"logVerbosity", LOG_VERBOSITY},
        {"selectedFontPath", SELECTED_FONT_PATH},
        {"logLevelP", LOG_LEVEL_PRINT},
        {"logLevelF", LOG_LEVEL_FILE},
        {"developerModeEnabled", DEVELOPER_MODE_ENABLED},
        {"cpuAndMemoryDisplayEnabled", CPU_AND_MEMORY_DISPLAY_ENABLED},
        {"sshEnabled", SSH_ENABLED},
        {"wifiEnabled", WIFI_ENABLED},
        {"wifiSSID", WIFI_SSID},
        {"wifiPassword", WIFI_PASSWORD},
        {"btEnabled", BT_ENABLED},
        {"statusIPAddress", STATUS_IP_ADDRESS},
        {"statusWifiMACAddress", STATUS_WIFI_MAC_ADDRESS},
        {"statusBTMACAddress", STATUS_BT_MAC_ADDRESS},
        {"statusFCCID", STATUS_FCC_ID},
        {"idleAnimationEnabled", IDLE_ANIMATION_ENABLED},
        {"idleAnimation", IDLE_ANIMATION},
        {"screenBrightness", SCREEN_BRIGHTNESS},
        {"screenAutoOff", SCREEN_AUTO_OFF},
        {"screenAutoOffTime", SCREEN_AUTO_OFF_TIME},
        {"notificationsFromNetworkEnabled", NOTIFICATIONS_FROM_NETWORK_ENABLED},
        {"systemVolume", SYSTEM_VOLUME},
        {"notificationSound", NOTIFICATION_SOUND},
        {"alarmSound", ALARM_SOUND},
        {"voiceCommandSound", VOICE_COMMAND_SOUND},
        {"nfcEnabled", NFC_ENABLED},
        {"microphoneEnabled", MICROPHONE_ENABLED},
        {"presenceDetectionEnabled", PRESENCE_DETECTION_ENABLED}
    };