name: tests

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo ./install-deps.sh
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TOOLING_SCRIPTS=OFF -DENABLE_BUILD_SERVER=OFF
      - name: Build
        run: cmake --build build -j
      - name: Run tests
        run: ctest --test-dir build -C Debug -j
