name: tests

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30   # ↑ allow cold builds to finish
    env:
      CC: gcc
      CXX: g++
      # Limit parallelism to fit the 2-core/7GB runner and avoid OOM
      JOBS: 2
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      CMAKE_DL_DIR: ${{ github.workspace }}/.cache/cmake
      FETCHCONTENT_BASE_DIR: ${{ github.workspace }}/.cache/cmake
      CPM_SOURCE_CACHE: ${{ github.workspace }}/.cache/CPM
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Capture compiler versions
        id: compver
        shell: bash
        run: |
          echo "gcc=$(/usr/bin/gcc -dumpfullversion -dumpversion)" >> $GITHUB_OUTPUT
          echo "gpp=$(/usr/bin/g++ -dumpfullversion -dumpversion)" >> $GITHUB_OUTPUT

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-gcc${{ steps.compver.outputs.gcc }}-gpp${{ steps.compver.outputs.gpp }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-ccache-gcc${{ steps.compver.outputs.gcc }}-gpp${{ steps.compver.outputs.gpp }}-
            ${{ runner.os }}-ccache-

      - name: Restore CMake/FetchContent downloads
        uses: actions/cache@v4
        with:
          path: |
            .cache/cmake
            .cache/CPM
          key: ${{ runner.os }}-cmake-dl-gcc${{ steps.compver.outputs.gcc }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-cmake-dl-gcc${{ steps.compver.outputs.gcc }}-
            ${{ runner.os }}-cmake-dl-

      - name: Restore CMake build directory
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-gcc${{ steps.compver.outputs.gcc }}-Debug-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', 'install-deps.sh', '.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-build-gcc${{ steps.compver.outputs.gcc }}-Debug-
            ${{ runner.os }}-build-

      - name: Install dependencies (system + ninja + ccache)
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
          sudo ./install-deps.sh
          ccache --set-config=max_size=500M || true
          ccache --zero-stats || true
          ccache --show-config || true

      - name: Create SSL certs
        run: |
          cd ssl
          ./generateCert.sh
          cd ..

      - name: Copy env file
        run: cp .env.example .env

      - name: Configure (Ninja + ccache)
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DENABLE_TOOLING_SCRIPTS=OFF
          -DENABLE_BUILD_SERVER=OFF
          -DBUILD_BT_MANAGER=OFF
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_DOWNLOAD_DIRECTORY="${CMAKE_DL_DIR}"
          -DFETCHCONTENT_BASE_DIR="${FETCHCONTENT_BASE_DIR}"

      - name: Build
        timeout-minutes: 25     # ↑ was 10; let cold cache builds finish
        run: cmake --build build --target CubeCoreTests --parallel ${JOBS}

      - name: ccache statistics (post-build)
        if: always()
        run: ccache -s || true

      - name: Run tests
        run: ctest --test-dir build -C Debug -j ${JOBS} --output-on-failure
